### ISSUE TITLE
Excel тайлангийн форматыг янзлах

### ISSUE THREAD

**Issue by peakdot** [skele2k/FAS#10]
- [x] Өдрийг урд нь гаргах
- [x] Тасгийн ID-г нэрээр нь солих
- [x] Нэр дээр ID гарч байгааг засах
- [ ] Эхлээд тасгаар, дараа нь нэрээр эрэмбэлэх
- [ ] Шинэ sheet-нд ч юм уу тэдэн цаг ажиллахаас тэдэн цаг ажилласан гээд тооцоо байж байвал зүгээр байх
- [ ] Өдөр өдрийн төлөвийг ер нь нэг өнгөөр ялгаад нэг баганад харуулвал харахад маш хялбар болох юм байна. (Жишээ нь 4-өөс бага цаг ажилласан бол улаан, 4-өөс их буюу хоцорсон бол шар, цагтаа бүрэн байсан бол өнгөгүй г.м)

**Comment by skele2k** [comment]
ustgagdsan tasag, ner hoyor ni id gaaraa garch baigaa.
