### ISSUE TITLE
Хурууны хээ уншдаг хэсэгт буруу IP оруулахад эхний цонх руу буцдаг болгох

### ISSUE THREAD

**Issue by peakdot** [skele2k/FAS#2]
Одоо IP буруу хийхээр Alert нь гарч ирээд дараагийн цонх руу шилжиж байна. Тэгээд IP товч дээр дараад IP-гаа солихоор ахиж холбогдох гэж оролдохгүй асуудалтай юм.

**Comment by skele2k** [comment]
ene hesgiig zaschihlaa. ta shalgaad hariu bicheerei
