### ISSUE TITLE
Бүх Form-ын Field дээр юм бичээд Enter дарахад Submit хийдэг байх (Web шиг)

### ISSUE THREAD

**Issue by peakdot** [skele2k/FAS#8]

**Comment by skele2k** [comment]
tegehleer neg asuudal baina. Huruuni heeg ni yah uu?

**Comment by peakdot** [comment]
Nemeh darahad shalgaj baigaa function-aa duudaad gaigui yum bishu

**Comment by skele2k** [comment]
aan boloh l ym baina.

**Comment by skele2k** [comment]
enter darahin orond button dardag bolgotson shuu
